url: https://mizrael.github.io/OpenSleigh
plugins:
  - jekyll-sitemap
  - jekyll-relative-links
  
google_analytics: G-V6KPT320HR
theme: jekyll-theme-architect

title: OpenSleigh
tagline: Yet another Saga management library for .NET Core.
description: A simple yet powerful Saga management, Workflow orchestration, pub/sub library for .NET Core.

twitter:
  username: DavideGuida82
  card: summary

author:
  twitter: DavideGuida82

github:
  repository_url: https://github.com/mizrael/OpenSleigh
  repository_name: OpenSleigh
  owner_url: https://www.davidguida.net
  owner_name: David Guida