coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 1%

ignore:
  - "tests/**"
  - "samples/**"
  - "**/*.Tests/**"
  - "**/E2ETests/**"

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false