<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <PackageVersion>3.0.4</PackageVersion>
    <CSharpLanguageVersion>12</CSharpLanguageVersion>
    <TargetFrameworkVersion>net9.0</TargetFrameworkVersion>
    <RepositoryUrl>https://github.com/mizrael/OpenSleigh</RepositoryUrl>
    <PackageProjectUrl>https://opensleigh.gitbook.io/</PackageProjectUrl>
  </PropertyGroup>
</Project>
