<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFrameworks>$(SupportedTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'OpenSleigh.Samples.Sample2.API' " />
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\OpenSleigh.Persistence.PostgreSQL\OpenSleigh.Persistence.PostgreSQL.csproj" />
    <ProjectReference Include="..\..\..\src\OpenSleigh.Persistence.SQL\OpenSleigh.Persistence.SQL.csproj" />
    <ProjectReference Include="..\..\..\src\OpenSleigh.Transport.RabbitMQ\OpenSleigh.Transport.RabbitMQ.csproj" />
    <ProjectReference Include="..\OpenSleigh.Samples.ECommerce.Common\OpenSleigh.Samples.ECommerce.Common.csproj" />
  </ItemGroup>

</Project>
