version: '3.4'

services:
  openSleigh.sample2.infrastructure.mongodb:
    image: mongo:latest
    container_name: openSleigh.sample2.infrastructure.mongodb    
    restart: always
    ports:
        - 27017:27017    
  
  openSleigh.sample2.infrastructure.rabbitmq:        
    image: rabbitmq:3-management-alpine
    container_name: openSleigh.sample2.infrastructure.rabbitmq    
    restart: always
    environment:
     RABBITMQ_DEFAULT_VHOST: "/opensleigh-sample2"
    ports:     
      - "15671:15671"
      - "15672:15672"   
      - "5672:5672"